import 'unittest' as unittest

class Exception_a : Exception {}

class Exception_b : Exception {}

var exception_a_handler_hit = false
var exception_a_finally_hit = false
var exception_b_finally_hit = false


function function_a()
{
    try
    {
        function_b()
    }
    catch (Exception_a as ex)
    {
        exception_a_handler_hit = true
    }
    finally
    {
        exception_a_finally_hit = true
    }
}

function function_b()
{
    try
    {
        function_c()
    }
    catch (Exception_b)
    {
        unittest.Assert.fail()
    }
    finally
    {
        exception_b_finally_hit = true
    }
}

function function_c()
{
    throw Exception_a()
}


function test_complex_exceptions() {
    function_a()
    unittest.Assert.that(exception_a_handler_hit).is_true()
    unittest.Assert.that(exception_a_finally_hit).is_true()
    unittest.Assert.that(exception_b_finally_hit).is_true()
}
