import 'unittest' as unittest

function test_throwing_exceptions() {
    unittest.Assert.that(| | {
        throw Exception()
    }).throws()
}

